language: php

php:
    - 7
    - hhvm

matrix:
    allow_failures:
        - php: hhvm


before_script:
    - composer update

script:
    - ./vendor/bin/phpunit --coverage-clover ./build/clover.xml
    - if [ $TRAVIS_PHP_VERSION != 'hhvm' ] && [ $TRAVIS_PHP_VERSION != '7' ]; then php build/coverage-checker.php build/clover.xml 70; fi
    - ./vendor/bin/phpcs --standard=PSR2 ./lib/ ./tests/OnurbTest/

after_script:
    - if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover ./build/clover.xml; fi
